---
title: "Evidentiality in the tense system"
author: "Samira Verhees"
output: html_document
link-citations: true
---

---------------------------------------

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

# packages

library(tidyverse)
library(lingtypology)
library(DT)

# load data

vill <- read_tsv("data/villages_old.csv") # villages dataset
meta <- read_tsv("data/meta_old.csv") # language metadata and colors
perfect <- read_tsv("data/features/tables/perfects.csv") # feature dataset

# preparation of data

vill <- vill[complete.cases(vill$lat),] # remove villages for which we do not have coordinates (yet)

meta_core <- meta %>% # remove idioms not (yet) recognized as distinct
  filter(core == "yes")

vill_meta <- merge(vill, meta_core, by = "lang") # merge villages and coordinates with language metadata

perfect_core <- perfect %>%
  filter(core == "yes")

perfect_vill <- merge(vill_meta, perfect_core, by = "lang") # merge villages, coordinates, and language metadata with feature information

perfect_vill$datapoint <- "extrapolated datapoint"

```

## Maps

See the chapter [here](evidentiality_tense.html).

### Map 1. Evidentiality as a function of the perfect{.tabset .tabset-fade .tabset-pills}

#### Map: Extrapolated data

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width = 9.5}

map.feature(lang.gltc(perfect_vill$glottocode),
            latitude = perfect_vill$lat,
            longitude = perfect_vill$lon,
            features = perfect_vill$lang, # color feature = language
            color = perfect_vill$lang_color,
            stroke.features = perfect_vill$`value:indir`, # stroke.feature = your feature value
            stroke.color = c("black", "white"), 
            label = perfect_vill$lang,
            zoom.control = T,
            popup = paste("<b>Village:</b>", perfect_vill$village, "<br>", 
                          "<b>Source:</b>", perfect_vill$source, perfect_vill$page, "<br>",
                          "<b>Datapoint:</b>", perfect_vill$datapoint),
            width = 3, stroke.radius = 8,
            legend = FALSE)
```

#### Map: General datapoints

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width = 9.5}

perfect_core_meta <- merge(perfect_core, meta_core, by = "lang")

perfect_core_meta$datapoint <- "general datapoint"

map.feature(lang.gltc(perfect_core_meta$glottocode),
            features = perfect_core_meta$lang,
            color = perfect_core_meta$lang_color,
            legend = FALSE,
            stroke.features = perfect_core_meta$`value:indir`,
            stroke.color = c("black", "white"),
            label = perfect_core_meta$lang,
            zoom.control = T,
            popup = paste("<b>Source:</b>", perfect_core_meta$source, perfect_core_meta$page, "<br>",
                          "<b>Datapoint:</b>", perfect_core_meta$datapoint))

```

### Map 2. Evidentiality within the tense system{.tabset .tabset-fade .tabset-pills}

#### Map: Extrapolated data

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width = 9.5}

map.feature(lang.gltc(perfect_vill$glottocode),
            latitude = perfect_vill$lat,
            longitude = perfect_vill$lon,
            features = perfect_vill$lang, # color feature = language
            color = perfect_vill$lang_color,
            stroke.features = perfect_vill$`value:evsystem`, # stroke.feature = your feature value
            stroke.color = c("black", "white"), 
            label = perfect_vill$lang,
            zoom.control = T,
            popup = paste("<b>Village:</b>", perfect_vill$village, "<br>", 
                          "<b>Source:</b>", perfect_vill$source, perfect_vill$page, "<br>",
                          "<b>Datapoint:</b>", perfect_vill$datapoint),
            width = 3, stroke.radius = 8,
            legend = FALSE)
```

#### Map: General datapoints

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width = 9.5}

perfect_core_meta <- merge(perfect_core, meta_core, by = "lang")

perfect_core_meta$datapoint <- "general datapoint"

map.feature(lang.gltc(perfect_core_meta$glottocode),
            features = perfect_core_meta$lang,
            color = perfect_core_meta$lang_color,
            legend = FALSE,
            stroke.features = perfect_core_meta$`value:evsystem`,
            stroke.color = c("black", "white"),
            label = perfect_core_meta$lang,
            zoom.control = T,
            popup = paste("<b>Source:</b>", perfect_core_meta$source, perfect_core_meta$page, "<br>",
                          "<b>Datapoint:</b>", perfect_core_meta$datapoint))

```

## Datatable

````{r}

# select which feature data you want to show in the datatable

dtable <- perfect %>%
  select(lang, idiom, form, `value:indir`, serial, source, page)

# generate searchable datatable

DT::datatable(dtable, escape = TRUE, rownames = TRUE,
              options = list(pageLength = 15, dom = 'ftip'))
```

## References