---
title: "Evidentiality in the tense system"
author: "Samira Verhees"
output: html_document
bibliography: ./data/features/ref_bibs/evidentiality.bib
link-citations: true
---

---------------------------------------

# Chapter

See [data and maps](evidentiality_tense_map.html).

General chapter: [Evidentiality](evidentiality.html)

## Introduction

Evidentiality as part of the tense system appears primarily as a function of the perfect. All East Caucasian languages have at least one verb form resembling the perfect as a cross-linguistic category [@verhees2019b: 52]. Not all of them express (indirect) evidentiality (see chapter [The perfect](perfect.html)).

Perfects in their prototypical use mark the current relevance of a past event. The sentence <i>Ali has dug a pit</i> implies that there is a pit at the moment of speech. The same sentence with simple past <i>Ali dug a pit</i> simply indicates that the event of Ali digging a pit took place in the past. It does not imply that the result is still there, or that Ali necessarily finished it.

The perfect's focus on a resulting situation can give rise to the implicature that the speaker had direct access to the current result and by contrast did not witness the event leading up to it. In other words, the speaker witnessed a result, from which they infer that an event took place (inferential).

(@one) Bagvalal [@tatevosov2007: 391]

<ul>
<table> 
  <tr>
	<td><i>ˁisa-r&nbsp;</td></i> <td><i>gandʷiː&nbsp;</td></i> <td><i>b-aqʷa-<b>m-o</b>&nbsp;</td></i> <td><i><b>ek’ʷa</b>&nbsp;</td></i> 
	</tr>
	<tr>
	<td>isa-erg&nbsp;</td> <td>pit&nbsp;</td> <td>n-dig-n-pfv.cvb&nbsp;</td> <td>cop&nbsp;</td>
	</tr>
	<tr>
	<td colspan="3">‘Isa <b>has dug</b> a pit.’ (the speaker infers this based on a result)</td>
  </tr>
</table>
</ul>

Example (@one) with the Bagvalal Perfect would be appropriate, for example, if the speaker had some knowledge that Isa was going to dig a pit, then witnessed the result (the pit is ready) and reaches the conclusion that Isa has dug the pit. According to Татевосов [-@tatevosov2007: 391], this utterance would be ungrammatical in a situation where the speaker witnessed how the final stage of the process unfolded. The English Present Perfect is not subject to such restrictions, since it is not on the path of development towards indirect evidentiality. At the same time, many of the East Caucasian perfects that have an indirect evidential function, to some degree also preserve current relevance uses (discussed in more detail in chapter [The perfect](perfect.html)).

The inferential interpretation can grammaticalize, and further the form may expand its usage to situations where the speaker did not have direct access to the event at all, for example because they know about it through hearsay (reportative). Note that the form itself stays unspecified, and the type of access the speaker had to the event has to be understood from the context. 

Perfects that are compatible with a hearsay reading often become conventionalized as a narrative tense for fairy tales, local legends, and other stories about events the speaker did not witness personally. Example (@two) is from a tale about Mullah Nasreddin, who was praying (out loud) to Allah for money. Each main clause in example (@two) is headed by a perfect. In this context the perfect functions as an unwitnessed perfective past, since current relevance forms cannot head narrative sequences [@lindstedt2000: 371].

(@two) Agul: Huppuq [@maisakmerdanova2016: 401]

<ul>
<table> 
  <tr>
<td><i>me&nbsp;</td></i> <td><i>un-x.u-<b>naa</b>&nbsp;</td></i> <td><i>me&nbsp;</td></i> <td><i>dak'ar.i&nbsp;</td></i>
</tr>
<tr>
<td>demm&nbsp;</td> <td>sound_become.pfv-res&nbsp;</td> <td>demm&nbsp;</td> <td>window(gen)&nbsp;</td>
</tr>
<tr>
<td><i>k'en.a-k-as&nbsp;</td></i> <td><i>ti-č&nbsp;</td></i> <td><i>ʕʷ.a-je&nbsp;</td></i> <td><i>sa&nbsp;</td></i>
</tr>
<tr>
<td>below-sub/cont-elat&nbsp;</td> <td>demt-lat&nbsp;</td> <td>go.ipfv-pt:prs&nbsp;</td> <td>one&nbsp;</td>
</tr>
<tr>
<td><i>kas.tːi-s.&nbsp;</td></i>
</tr>
<tr>
<td>person-dat&nbsp;</td>
</tr>
<tr>
<td><i>mi=ra&nbsp;</td></i> <td><i>ʁuš.u-na&nbsp;</td></i> <td><i>uč.i-n&nbsp;</td></i> <td><i>košelëk.tːi-ʔ&nbsp;</td></i>
</tr>
<tr>
<td>demm(erg)=add&nbsp;</td> <td>take.pfv-cvb&nbsp;</td> <td>self-gen&nbsp;</td> <td>wallet-in&nbsp;</td> 
</tr>
<tr>
<td><i>ik'.i-<b>naa</b>&nbsp;</td></i> <td><i>jaq'uqːa-n=na&nbsp;</td></i> <td><i>c'ejarč'ʷa&nbsp;</td></i> <td><i>manat,&nbsp;</td></i>
</tr>
<tr>
<td>put.pfv-res&nbsp;</td> <td>80-s=and&nbsp;</td> <td>19&nbsp;</td> <td>ruble&nbsp;</td>
</tr>
<tr>
<td><i>fatx.i-<b>naa</b>&nbsp;</td></i> <td><i>kürmeʕ.i-as&nbsp;</td></i> <td><i>aq&nbsp;</td></i>
</tr>
<tr>
<td>throw.pfv-res&nbsp;</td> <td>chimney-(in)elat&nbsp;</td> <td>down&nbsp;</td>
</tr>
<tr>
<td><i>malla&nbsp;</td></i> <td><i>nesredil.a-s&nbsp;</td></i>
</tr>
<tr>
<td>Mullah&nbsp;</td> <td>Nasreddin-dat&nbsp;</td>
</tr>
<tr>
<td><i>ahaʔ&nbsp;</td></i> <td><i>p.u-<b>naa</b>&nbsp;</td></i> <td><i>malla&nbsp;</td></i> <td><i>nesredil.a,&nbsp;</td></i>
</tr>
<tr>
<td>intj&nbsp;</td> <td>say.pfv-res&nbsp;</td><td>Mullah&nbsp;</td> <td>Nasreddin(erg)&nbsp;</td> 
</tr>
<tr>
<td><i>ze-f&nbsp;</td></i> <td><i>ad.i-ne.&nbsp;</td></i>
</tr>
<tr>
<td>my-s&nbsp;</td> <td>come.pfv-aor&nbsp;</td>
</tr>
	<tr>
	<td colspan="4">‘One person, who walked past the window, <b>heard</b> this. He <b>put</b> 99 ruble in his wallet and <b>threw</b> it at Mullah Nasreddin through the chimney. "Aha," <b>said</b> Mullah Nasreddin, "this is for me".’</td>
  </tr>
</table>
</ul>

Indirect evidential perfects commonly carry additional overtones that may develop into independent meanings. These include <b>mirativity</b> (information is new and / or unexpected) and <b>epistemic modality</b> (the speaker does not vouch for the veracity of the information). In example (@three) the speaker talks about a wedding where they received a shawl as a gift, which is not in accordance with their social status. The Tsakhur Perfect in this case marks the speaker's surprise (mirativity).

(@three) Tsakhur: Mishlesh [@maisaktatevosov2007: 386]

<ul>
<table> 
  <tr>
  <td><i>za-s&nbsp;</td></i> <td><i>jaːluʁ&nbsp;</td></i> <td><i><b>wo-b</b>&nbsp;</td></i>
  </tr>
  <tr>
  <td>1sg.obl-dat&nbsp;</td> <td>shawl.3&nbsp;</td> <td>aux-3&nbsp;</td>
  </tr>
  <tr>
  <td><i><b>qa-b-ɨ</b>;&nbsp;</td></i> <td><i>turs-ubɨ&nbsp;</td></i> <td><i>qal-es-di&nbsp;</td></i> </tr>
  <tr>
  <td>prf-3-bring.pfv&nbsp;</td> <td>woolen_sock-pl&nbsp;</td> <td>npl.bring-pt-a.obl&nbsp;</td>
  </tr>
  <tr>
  <td><i>ǯiqj-eː&nbsp;</td></i> <td><i>jaːluʁ<b>-o-b</b>&nbsp;</td></i> <td><i><b>qa-b-ɨ</b>.&nbsp;</td></i>
  </tr>
  <tr>
  <td>place-in&nbsp;</td> <td>shawl.3-aux-3&nbsp;</td> <td>prf-3-bring.pfv&nbsp;</td>
   </tr>
  <tr>
  <td colspan="3">‘(they) <b>brought</b> me a shawl; instead of (lit. in place of bringing) woolen socks, (they) <b>brought</b> a shawl.’ (Woolen socks are considered to be more valuable than a shawl.)</td>
  </tr>
</table>
</ul>  
  
Some authors prefer to describe this complex of meanings as components of a more general, abstract category.[^1] The prominence of each of these meanings seems variable across languages, and there appears to be no empirically reliable method to compare their configuration.

[^1]: For example indirective [@johanson2000], mediative [@lazard1999], non-confirmative [@friedman2000].

The aim of this chapter is to show the distribution of indirect evidentiality within the tense system and as a meaning of the perfect. The semantics and pragmatics of these phenomena will not be discussed further due to a lack of data.

## Summary

Perfects with an indirect evidential function are attested in 37 idioms of 24 languages. 2 idioms (Zaqatala Avar and Axaxdɘrɘ Akhvakh) feature a suffix of unclear etymological origin to mark indirect evidential past.

Following the grammaticalization of the perfect, the category of evidentiality can spread through the past tense paradigm. First, the general past tense can become reanalyzed as a direct evidential (i.e. witnessed) past. This appears to have occurred in the Nakh and Tsezic languages, though see [@forker2018a] for discussion. In other languages the indirect evidential form is opposed by evidentially neutral tenses.

Second, the indirect evidential feature can spread to other tense-aspect forms. In at least 15 idioms a perfect form of the auxiliary derives the indirect evidential counterparts of direct or neutral past tenses with an auxiliary inflected for general past.[^2] These parallel paradigms are often referred to as "series". Table 1. below shows a partial illustrative paradigm for Avar.

Table 1. Past tenses in Avar: Aorist and Perfect series

|              |Aorist                      |Perfect                          |
|--------------|----------------------------|---------------------------------|
|Aorist/Perfect|c'al-<b>ana</b>             |c'al-<b>un b-ugo</b>             |
|              |read-aor                    |read-cvb n-cop                   |
|Pluperfect    |c'al-un <b>b-uk'-ana</b>    |c'al-un <b>b-uk'-un b-ugo</b>    |
|              |read-cvb n-be-aor           |read-cvb n-be-cvb n-cop          |
|Imperfect     |c'al-ul-e-b <b>b-uk'-ana</b>|c'al-ul-e-b <b>b-uk'-un b-ugo</b>|
|              |read-prs-ptcp-n n-be-aor    |read-prs-ptcp-n n-be-cvb n-cop   |

[^2]: I use the term “general past” here to refer to the single most frequent and least morphologically and functionally marked past tense. Language descriptions may label the same form Aorist, Preterite, or Perfective Past, depending on the specifics of the language. 

Divergent paradigms are found in Chechen and Tsakhur. Indirect evidential past tenses in Chechen (which contrast with direct evidential and neutral tenses) are derived with different forms of a special auxiliary <i>xil-</i> (‘be, become’) [@molochieva2007]. In Chechen the evidential value is thus connected to the lexical item, rather than its inflectional form. Because the indirect evidential past in Chechen structurally looks like a pluperfect with a perfect auxiliary (cf. example (@four) and the Perfect Pluperfect in Table 1), I argued in Ферхеес [-@verhees2019b: 85-86] that the Chechen system probably also has its roots in the path from perfect to indirect evidentiality.

(@four) Standard Chechen [@molochieva2010: 54]

<ul>
<table> 
  <tr>
  <td><i>dada-s&nbsp;</td></i> <td><i>jol&nbsp;</td></i> <td><i><b>hwiaq-na</b>&nbsp;</td></i> <td><i><b>xilla</b>&nbsp;</td></i>
    </tr>
  <tr>
  <td>father-erg&nbsp;</td> <td>hay.nom(j)&nbsp;</td> <td>rub:pfv1-cvb&nbsp;</td> <td>be.prf&nbsp;</td>
  </tr>
  <tr>
   <td colspan="3">‘Father has cut/made hay.’ (The speaker did not see it.)</td>
  </tr>
</table>
</ul>  

Indirect evidential tenses in Tsakhur are formed with a non-attributivized (NAF) form of the copula <i>wo-d</i>, as opposed to the attributivized (AF) copula, which derives their neutral counterparts.[^3] Another peculiarity of the system in Tsakhur is that it is not limited to the past tense domain. In example (@five) the speaker is talking about a dream they had. Events witnessed in dreams are typically rendered with indirect forms in Tsakhur. In this case, the NAF Durative (a present progressive form) is used.

[^3]: The terms attributivized and non-attributivized (AF and NAF in [@maisaktatevosov2007]) refer strictly to the morphological form. AF can head independent main predicates and are not necessarily attributive.

(@five) Tsakhur: Mishlesh [@maisaktatevosov2007: 383]

<ul>
<table> 
  <tr>
  <td><i>zɨ&nbsp;</td></i> <td><i><b>alljhaː</b>&nbsp;</td></i> <td><i><b>wo-r</b>&nbsp;</td></i> <td><i>č'alag-a-nče.&nbsp;</td></i>
  </tr>
  <tr>
  <td>1sg.1&nbsp;</td> <td>1.go.ipfv&nbsp;</td> <td>aux-1&nbsp;</td> <td>forest-in-el&nbsp;</td>
  </tr>
  <tr>
  <td><i>birdan&nbsp;</td></i> <td><i>za-k'le&nbsp;</td></i> <td><i>ɢaǯe-n..&nbsp;</td></i>
  </tr>
  <tr>
  <td>suddenly&nbsp;</td> <td>1sg.obl-aff&nbsp;</td> <td>3.see.ipfv-a&nbsp;</td>
  </tr>
  <tr>
   <td colspan="3">‘I'<b>m walking</b> through the forest. Suddenly I see that...’ </td>
  </tr>
</table>
</ul>  

Note that according to Maisak and Tatevosov [-@maisaktatevosov2007: 378], this system also results from diachronic developments of the perfect, only instead of a reanalysis of the perfect inflection (i.e. a periphrastic structure consisting of a perfective converb and a NAF copula), the copula itself was reanalyzed as an indirect evidential marker. This interpretation is limited to periphrastic tenses: copular sentences with <i>wo-d</i> are neutral in terms of evidentiality.

Kumyk and Nogai also feature a verb form that combines prototypical perfect uses with indirect evidentiality. A copula inflected for this form (<i>bol-ʁan</i> in Kumyk, <i>e-ken</i> in Nogai) derives further indirect evidential tenses. 

In Azerbaijani the perfect expresses only current relevance. This is most likely the result of a loss, since the evidential function of the <i>-mIš</i> past in Turkic is quite old.[^4] The corresponding form from Turkish -- a closely related and mutually intelligible Turkic language -- is an indirect evidential past that is considered to have its origins in a perfect [@slobinaksukoc1982: 188-190]. Azerbaijani does retain the indirect evidential copular particle <i>-(i)mIš</i> (a Turkic equivalent of the perfect auxiliaries found in East Caucasian). The presence of this form would be hard to explain if the Azerbaijani <i>-mIš</i> past never had an indirect evidential function. According to Johanson [-@johanson2018: 514], the Azerbaijani perfect became a current relevance form under the influence of Persian, though this seems at odds with accounts describing the Persian perfect as having an indirect evidential function [@lazard2000].

[^4]: This function of the <i>-mIš</i> past is already attested in early Turkic texts of the 8-13 centuries, see Erdal [-@erdal2004: 273].

## Areal distribution

Evidentiality as part of the tense system and as a function of the perfect shows a peculiar areal distribution in the eastern Caucasus: it is overall common but notably absent in the southern part of the area. This is not due to a lack of description, see Maisak [-@maisakunpub].

The distribution of these features appears to correspond to the spread of different Turkic languages as lingua franca. Many East Caucasian people would acquire a command of Kumyk or Nogai through trade at the important local markets of Mozdok, Kizlyar, and Buynaksk in the northwestern and central parts of the eastern Caucasus [@wixman1980: 58-59]. Male Daghestanian highlanders could also pick up Kumyk through pastorialism in the central lowlands, which were dominated by Kumyk speakers [@wixman1980: 57, 71]. Azerbaijani was the main lingua franca at the market of Derbent in the south [@wixman1980: 58-59]. It also functioned as the language of literacy for most Lezgic people (see various chapters in Арутюнов и др. [-@arutjunovetal2002]). Overall the influence of Azerbaijani in the south seems more substantial than the influence of Kipchak languages in the northern and central areas. Bilingualism rates for Azerbaijani are much higher [@multidag], and influence on grammatical structure is well-attested (see Aristova [-@aristova2019]), while the linguistic influence of Kipchak languages seems limited to lexical borrowings.

Despite the striking distribution of these features, a number of factors prevent the straightforward reconstruction of a contact scenario:

- The pattern does not match the bilingual zones perfectly: Tsakhur and Agul have the feature while they belong to the Azerbaijani zone of influence
- The hypothesis implies a significant structural influence of the Kipchak languages on East Caucasian, for which there is little supporting evidence in the form of structural borrowing in other domains or evidence of widespread and intense bilingualism
- It is not evident that the Kipchak forms could have served as a productive borrowing model for the East Caucasian perfects: the latter are predominantly periphrastic constructions, while the Kipchak forms are synthetic
- The development from perfect to indirect evidentiality does not occur exclusively as the result of language contact. It can develop language-internally. Without sufficient evidence to support an alternative scenario, this possibility cannot be ruled out

## Related features

- [The perfect](perfect.html)
- [Particles of reported speech and inference](particles.html)
- [Evidential auxiliaries](evidentiality_tense.html)

## References

