---
title: "The perfect"
author: "Samira Verhees"
output: html_document
bibliography: ./data/features/ref_bibs/evidentiality.bib
link-citations: true
---
---------------------------------------

# Chapter

See maps [here](perfect_map.html).

## Introduction

The perfect indicates the current relevance of an event completed in the past. The sentence in example (@one) with the Botlikh Perfect could be uttered, for example, in reply to a question whether the speaker is hungry or wants something to eat.

(@one) Botlikh [@alexeyevverheesunpub]

<ul>
<table> 
  <tr>
	<td><i>den&nbsp;</td></i> <td><i>henala&nbsp;</td></i> <td><i><b>inku-j-č'a</b>&nbsp;</td></i> <td><i><b>ida</b>&nbsp;</td></i>
	</tr>
  <tr>
  <td>I&nbsp;</td> <td>still&nbsp;</td> <td>eat-is-neg.cvb&nbsp;</td> <td>cop&nbsp;</td>
  </tr>
  <tr>
		<td colspan="3">‘I <b>haven't eaten</b> yet.’ (so I could eat something now) </td>
  </tr>
</table>
</ul>

Current relevance is an umbrella-term subsuming several more specific meanings [@ritz2012: 882-883; @mccawley1971; @comrie1976]:

- Resultative perfect -- <i>Patimat <b>has broken</b> her arm.</i> (the arm is now broken)
- Continuative -- <i>Patimat <b>has lived</b> in the village for 40 years.</i> (and she still lives there)
- Experiential -- <i>Patimat <b>has been</b> to Japan.</i> (at least once in her life)
- “Hot news” perfect -- <i>Patimat <b>has</b> just <b>arrived</b>.</i>

In this chapter I will use the term perfect to refer to verb forms with a current relevance function.

Perfects are typically periphrastic forms [@bybeedahl1989: 56]. Common sources include resultative and completive constructions [@bybee1994: 105]. Only the former are relevant for the eastern Caucasus. Resultative constructions typically consist of (or derive from) a non-finite form with past or perfective semantics, and a stative auxiliary such as ‘be’ or ‘have’ with present tense reference [@bybee1994: 55--57].

<b>Resultative constructions</b> render a present state as the result of a past action [@nedjalkovjaxontov1988: 6]. They form monovalent, stative predicates, as in example (@two), and are mostly restricted to change-of-state verbs.[^1]

(@two) Avar [@verhees2018: 263]

<ul>
<table> 
  <tr>
	<td><i>nuc'a&nbsp;</td></i> <td><i>(žegi)&nbsp;</td></i> <td><i><b>qan</b>&nbsp;</td></i> <td><i><b>b-ugo</b>&nbsp;</td></i> 
	</tr>
  <tr>
  <td>door&nbsp;</td> <td>(still)&nbsp;</td> <td>close.cvb&nbsp;</td> <td>n-be.prs&nbsp;</td> 
  </tr>
  <tr>
		<td colspan="3">‘The door <b>is</b> (still) <b>closed</b>.’</td>
  </tr>
</table>
</ul>

[^1]: In East Caucasian certain present states are always rendered with a resultative form of an inchoative verb, because the languages lack a stative lexeme. These states include certain postures (‘standing’, ‘lying down’) and physical states (‘sleeping’, ‘being sick’). The exact inventory of such predicates in individual languages, as well as the set shared across the branches of the family, remains a topic for future investigation.

The <b>resultative perfect</b>, illustrated in example (@three), represents a more progressed stage of grammaticalization. In contrast to the resultative proper it maintains the argument structure of the original lexical verb [@plungian2016: 10]. The result is a less stative predicate that is incompatible with adverbs of unlimited duration like <i>žegi</i> ‘still’. Resultative proper and resultative perfect can be expressed by distinct constructions or with the same form.

(@three) Avar [@verhees2018: 263]

<ul>
<table> 
  <tr>
	<td><i>di-ca&nbsp;</td></i> <td><i>nuc'a&nbsp;</td></i> <td><i><b>qan</b>&nbsp;</td></i> <td><i><b>b-ugo</b>&nbsp;</td></i> 
	</tr>
  <tr>
  <td>I-erg&nbsp;</td> <td>door&nbsp;</td> <td>close.cvb&nbsp;</td> <td>n-be.prs&nbsp;</td> 
  </tr>
  <tr>
		<td colspan="3">‘I <b>have closed</b> the door.’</td>
  </tr>
</table>
</ul>

A perfect can subsequently develop other functions through conversational implicature, including: indirect evidentiality, mirativity, and epistemic modality (see chapter [Evidentiality in the tense system](evidentiality_tense.html)).

The aim of this chapter is to show the distribution of different formal structures (e.g. synthetic vs. periphrastic) and various possible functions of perfects.

## Summary

The dataset for this chapter contains 74 verb forms from 47 idioms.[^2] 10 of these verb forms appear to be dedicated resultative constructions that exist alongside a perfect. Possibly these forms have additional current relevance functions which are simply not described. Since we cannot be sure at this stage, they are discussed separately throughout this chapter. 10 other forms are only reported to have an indirect evidential function. 8 of these can be diachronically linked to the perfect through their formal appearance and comparison with closely related idioms. The remaining two cases are Axaxdɘrɘ Akhvakh and Zaqatala Avar, which both have an indirect evidential past suffix of unclear origins.

[^2]: The average number of forms is 1.5: 24 idioms have 1 form, 19 have 2, and 4 have 3.

### Structure

About half of the forms in the sample (32/64) are periphrastic while the rest is synthetic (31/64).[^3] Of 31 synthetic forms, 5 result from morphologization of the auxiliary. In 12 cases, the synthetic perfect coincides with a non-finite form. It would seem plausible to assume that this results from a dropped auxiliary, given that periphrastic constructions are rather common. This scenario can be confirmed for Hinuq and Tsez, where the auxiliary resurfaces under negation. In other cases, however, the alternative scenario -- syncretism through desubordination of a non-finite construction -- cannot be ruled out. The Udi perfect is formed with a suffix that possibly also traces back to a periphrastic construction, see Maisak [-@maisak2018: 158--160].

[^3]: Botlikh uses both options as free variants and is counted separately.

The lexical verb most commonly takes the form of a converb (37/64), while participles are less frequent (18/37).[^4] The main perfect form is based on a participle in Budukh, Armenian, and the Turkic languages. The auxiliary verb often takes the form of a defective copula ‘be’, ‘be at’ which can also head non-verbal predication. Dargwa varieties employ so-called predicative markers: a mixed paradigm of clitic person markers for first and second person and a copula for third person.

[^4]: The perfects of Ingush and Chechen are considered to be based on converbs, while the Bats perfect is analyzed as based on a participle. It actually concerns a set of cognate forms that can act as a converb and a participle in all three languages. In the dataset for this chapter they form a separate category. Another exception is Khinalug, where both attested perfects are based on the resultative stem of the lexical verb.

Among the resultative constructions 8/10 are periphrastic, and the proportion of converbs with respect to participles is 50-50 for this group. All of these constructions exist alongside a perfect in their respective languages.

### Semantics

Current relevance is widely attested, though it seems to be limited mostly to resultative perfect. This could be due to a lack of description.

Many of the perfect forms also preserve the narrow resultative function (35/64), cf. the resultative and resultative perfect uses of the Tabasaran Perfect in examples (@four) and (@five), respectively.

(@four) Tabasaran [@maisakunpub]

<ul>
<table> 
  <tr>
	<td><i>barχl.i-in&nbsp;</td></i> <td><i>muχ&nbsp;</td></i> <td><i><b>d-a(b)x-na</b>.&nbsp;</td></i>
	</tr>
  <tr>
  <td>carpet-super&nbsp;</td> <td>barley&nbsp;</td> <td>pv-(cl)pour.pfv-prf&nbsp;</td>
  </tr>
  <tr>
		<td colspan="3">‘There is barley (lit. barley <b>is poured</b>) on the carpet.’</td>
  </tr>
</table>
</ul>

(@five) Tabasaran [@maisakunpub]

<ul>
<table> 
  <tr>
	<td><i>uwu&nbsp;</td></i> <td><i>läχˁin&nbsp;</td></i> <td><i><b>d-ap'-na=wa</b>&nbsp;</td></i>
	</tr>
  <tr>
  <td>you&nbsp;</td> <td>work&nbsp;</td> <td>pv-do.pfv-prf=2sg&nbsp;</td>
  </tr>
  <tr>
	<td><i>hamus&nbsp;</td></i> <td><i>ʁaraχ&nbsp;</td></i> <td><i>sejir&nbsp;</td></i> <td><i>ap'-in!&nbsp;</td></i>
	</tr>
	<tr>
  <td>now&nbsp;</td> <td>go.away.imp&nbsp;</td> <td>walk&nbsp;</td> <td>do-imp&nbsp;</td>
  </tr>
  <tr>
		<td colspan="4">‘You <b>have done</b> your work, now go and take a walk!’</td>
  </tr>
</table>
</ul>

Continuative so far is attested only for Avar in [@verhees2018: 271] and this claim needs to be checked, since it reflects the speech of only one speaker.

(@six) Avar [@verhees2018: 271]

<ul>
<table> 
  <tr>
	<td><i>do-j&nbsp;</td></i> <td><i><b>j-alah-un</b>&nbsp;</td></i> <td><i><b>j-igo</b>&nbsp;</td></i> <td><i>ɬab-go&nbsp;</td></i> <td><i>saʕat-aɬ&nbsp;</td></i>
	</tr>
  <tr>
  <td>dem-f&nbsp;</td> <td>f-watch-cvb&nbsp;</td> <td>f-be.prs&nbsp;</td> <td>three-num&nbsp;</td> <td>hour-erg&nbsp;</td>
  </tr>
  <tr>
		<td colspan="3">‘She <b>has watched</b> [TV] for three hours (and she is still watching).’</td>
  </tr>
</table>
</ul>

The experiential function is usually expressed either by a perfective past or a dedicated construction (@seven). Exceptions include Bats, Kryz, Kumyk, and Udi.

(@seven) Dargwa: Shiri [@belyaev2018: 86]

<ul>
<table> 
  <tr>
	<td><i>di-la&nbsp;</td></i> <td><i>rucːi&nbsp;</td></i> <td><i><b>či(r)ag-ib-zi-w=di=w</b>&nbsp;</td></i> <td><i>ʕät?&nbsp;</td></i>
	</tr>
  <tr>
  <td>me-gen&nbsp;</td> <td>sister&nbsp;</td> <td>(f)see.pfv-ptcp-attr-m=2=gq&nbsp;</td> <td>thee.dat&nbsp;</td>
  </tr>
  <tr>
		<td colspan="3">‘<b>Have</b> you (ever) <b>seen</b> [i.e. <b>met</b>] my sister?’</td>
  </tr>
</table>
</ul>

The “hot news” perfect is only marginally attested. This could be due to the pragmatic nature of this function, which makes it difficult to detect and elicit.

(@eight) Udi: Nizh [@maisak2016: 340]

<ul>
<table> 
  <tr>
	<td><i>qːonaʁ-χo=ne&nbsp;</td></i> <td><i><b>har-e</b>!&nbsp;</td></i>
	</tr>
  <tr>
  <td>guest-pl=3sg&nbsp;</td> <td>come-prf&nbsp;</td>
  </tr>
  <tr>
		<td colspan="3">[What is that noise at the gates?] ‘The guests <b>have arrived</b>!’</td>
  </tr>
</table>
</ul>



Indirect evidentiality is generally common but notably absent in a particular area (see chapter [Evidentiality in the tense system](evidentiality_tense.html)).

## Areal distribution

The distribution of various functions associated with the perfect as a typological category do not give off a strong areal signal, with the exception of indirect evidentiality. Experiential constructions are not very common overall, though this could result from a lack of description. Structural parameters do not show a clear genealogical or areal pattern either.


## Related features

- [Evidentiality in the tense system](evidentiality_tense.html)
- [Particles of reported speech and inference](particles.html)
- [Evidential auxiliaries]()

## References