---
title: "Team"
output:
  html_document:
    include:
      in_header: ./html/header_team.html
---

***

[The TALD project](https://ilcl.hse.ru/en/projects/) would not have been realised in its present form without advice and assistance of a number of people. 

The project is led by [Michael Daniel](https://www.hse.ru/en/staff/michael_daniel), [George Moroz](https://www.hse.ru/en/org/persons/103489498), [Chiara Naccarato](https://www.hse.ru/en/org/persons/224233250), [Samira Verhees](https://www.hse.ru/en/staff/samiraverhees), and [Konstantin Filatov](https://www.hse.ru/en/org/persons/190921062).

[Chiara Naccarato](https://www.hse.ru/en/org/persons/224233250) and [Samira Verhees](https://www.hse.ru/en/staff/samiraverhees) coordinate the workshop for students.

Our consultants are: [Timur Maisak](https://www.hse.ru/en/staff/maisak), [Aigul Zakirova](https://www.hse.ru/en/org/persons/190888832).

Participants currently working on features are: [Nina Dobrushina](https://www.hse.ru/en/staff/dobrushina), [Evgeniya Klyagina](https://www.hse.ru/org/persons/224839526), [Timofey Mukhin](https://www.hse.ru/en/org/persons/208514310), [Polina Nasledskova](https://www.hse.ru/en/org/persons/190905106), [Ivan Netkachev](https://www.hse.ru/org/persons/190905500), Samira Ochs, [Anastasia Panova](https://www.hse.ru/en/staff/apanova), Sara Zadykian.

Students who have contributed in the past are: Denis Arsentjev, Fyodor Golosov, Violetta Ivanova, Inga Kartozia, Rita Popova.

[Timofey Mukhin](language.html) is responsible for the TALD website.

Photos presented on the site are taken by [Michael Daniel](https://www.hse.ru/en/staff/michael_daniel), [Timur Maisak](https://www.hse.ru/en/staff/maisak), [Timofey Mukhin](https://www.hse.ru/en/org/persons/208514310) and [Konstantin Filatov](https://www.hse.ru/en/org/persons/190921062).

## Contact us

You can always contact us via email at <cauatlas@gmail.com>.

***